apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
spec:
  containers:
    - name: elasticsearch
      image: 'dev-quay-registry.apps.k8sdevint.fzg.local/k8sdevint_corwiz-dev/library/elasticsearch:7.17.10'
      ports:
        - containerPort: 6377
