apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
spec:
  containers:
    - name: postgresql-13
      image: 'dev-quay-registry.apps.k8sdevint.fzg.local/k8sdevint_corwiz-dev/rhel9/postgresql-13:stable'
      env:
        - name: POSTGRES_USER
          value: test_user
        - name: POSTGRES_PASSWORD
          value: test_pw
      ports:
        - containerPort: 5432
