apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
spec:
  containers:
    - name: postgresql-container
      image: k8sdevint_corwiz-deb/rhel9/postgresql-13
      env:
        - name: POSTGRES_USER
          value: test_user
        - name: POSTGRES_PASSWORD
          value: test_pw
      ports:
        - containerPort: 5432
