apiVersion: v1
kind: Pod
metadata:
  name: postgresql-13
spec:
  containers:
    - name: postgresql-13
      image: 'dev-quay-registry.apps.k8sdevint.fzg.local/k8sdevint_corwiz-dev/rhel9/postgresql-13:1-124'
      env:
        - name: POSTGRESQL_USER
          value: test_user
        - name: POSTGRESQL_PASSWORD
          value: test_pw
        - name: POSTGRESQL_DATABASE
          value: test_db

      ports:
        - containerPort: 5432
