apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: redis-container
      image: https://dev-quay-registry.apps.k8sdevint.fzg.local/k8sdevint_corwiz-deb/rhel9/redis-6
      ports:
        - containerPort: 6379
