name: Build Docker Image

on: 
  push:
    branches:
      - main
    paths:
      - 'web_app.dockerfile'

jobs:
  build_web_app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build web_app image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./web_app.dockerfile
        push: false

    - name: Test build success
      run: echo "Build succeeded"

